### ISSUE TITLE
Don't crash if joining a room failed (due to the invite being revoked or otherwise)

### ISSUE THREAD

**Issue by turt2live** [shawnanastasio/matrix-pollbot#5]
Currently the bot crashes when it fails to join a room. This shouldn't be the case.

**Comment by shawnanastasio** [comment]
Could you copy/paste the error (if any) that prints out when this occurs?

Thanks.

**Comment by turt2live** [comment]
```
Got invite to room: !redacted:t2bot.io
Joining...
A MatrixRequestError occured during sync.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pollbot/matrix-pollbot/env/lib/python3.5/site-packages/matrix_client/client.py", line 346, in listen_forever
    raise e
  File "/home/pollbot/matrix-pollbot/env/lib/python3.5/site-packages/matrix_client/client.py", line 335, in listen_forever
    self._sync(timeout_ms)
  File "/home/pollbot/matrix-pollbot/env/lib/python3.5/site-packages/matrix_client/client.py", line 431, in _sync
    listener(room_id, invite_room['invite_state'])
  File "/home/pollbot/matrix-pollbot/env/lib/python3.5/site-packages/matrix_bot_api/matrix_bot_api.py", line 65, in handle_invite
    room = self.client.join_room(room_id)
  File "/home/pollbot/matrix-pollbot/env/lib/python3.5/site-packages/matrix_client/client.py", line 221, in join_room
    response = self.api.join_room(room_id_or_alias)
  File "/home/pollbot/matrix-pollbot/env/lib/python3.5/site-packages/matrix_client/api.py", line 161, in join_room
    return self._send("POST", path)
  File "/home/pollbot/matrix-pollbot/env/lib/python3.5/site-packages/matrix_client/api.py", line 536, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 403: {"errcode":"M_FORBIDDEN","error":"You are not invited to this room."}
```

This is based off of the code here: https://github.com/shawnanastasio/matrix-pollbot/pull/4

**Comment by shawnanastasio** [comment]
It seems that the issue is in the [python-matrix-bot-api](https://github.com/shawnanastasio/python-matrix-bot-api) project rather than this one. If you could open an issue there then we can resume diagnosing it. Thanks.

**Comment by turt2live** [comment]
It seems like this is more of a responsibility for the bot, not the API. The API is doing the right thing and throwing an exception, but the bot isn't handling it well.

The error is completely valid as well, the user isn't invited to the room anymore. The invitation was revoked between it being sent and it being acted upon.

**Comment by shawnanastasio** [comment]
It's a bit complicated, but basically, pollbot is built on top of python-matrix-bot-api which uses the matrix-python-sdk internally. python-matrix-bot-api provides some wrappers for matrix-python-sdk's functionality and it's what's in charge of joining rooms on behalf of the bot. The relevant code is [here](https://github.com/shawnanastasio/python-matrix-bot-api/blob/master/matrix_bot_api/matrix_bot_api.py#L62).
